@LivrariaAPI_HostAddress = http://localhost:5145

### Request para WeatherForecast
GET {{LivrariaAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

### CRUD Livros ###

# GET - Listar todos os livros
GET {{LivrariaAPI_HostAddress}}/api/livros
Accept: application/json

###

# POST - Adicionar um novo livro
POST {{LivrariaAPI_HostAddress}}/api/livros
Content-Type: application/json

{
  "titulo": "Senhor dos Aneis",
  "autor": "J. R. R. Tolkien",
  "genero": "Fantasia Medieval",
  "estoque": 10
}

###

# PUT - Atualizar um livro existente
PUT {{LivrariaAPI_HostAddress}}/api/livros/5
Content-Type: application/json

{
  "id": 1,
  "titulo": "O Hobbit",
  "autor": "J. R. R. Tolkien",
  "genero": "Fantasia",
  "estoque": 5
}

###

# DELETE - Excluir um livro existente
DELETE {{LivrariaAPI_HostAddress}}/api/livros/4

###

### CRUD Clientes ###

# GET - Listar todos os clientes
GET {{LivrariaAPI_HostAddress}}/api/clientes
Accept: application/json

###

# POST - Adicionar um novo cliente
POST {{LivrariaAPI_HostAddress}}/api/clientes
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@email.com"
}

###

# PUT - Atualizar um cliente existente
PUT {{LivrariaAPI_HostAddress}}/api/clientes/1
Content-Type: application/json

{
  "id": 1,
  "nome": "João Silva Atualizado",
  "email": "joao.silva@email.com"
}

###

# DELETE - Excluir um cliente existente
DELETE {{LivrariaAPI_HostAddress}}/api/clientes/1

###

### CRUD Pedidos ###

# GET - Listar todos os pedidos
GET {{LivrariaAPI_HostAddress}}/api/pedidos
Accept: application/json

###

# POST - Adicionar um novo pedido
POST {{LivrariaAPI_HostAddress}}/api/pedidos
Content-Type: application/json

{
  "clienteId": 1,
  "livros": [
    { "id": 7 }
  ],
  "dataPedido": "2024-09-24T00:00:00"
}

###

# PUT - Atualizar um pedido existente
PUT {{LivrariaAPI_HostAddress}}/api/pedidos/1
Content-Type: application/json

{
  "id": 1,
  "clienteId": 1,
  "livros": [
    { "id": 1 }
  ],
  "dataPedido": "2024-09-25T00:00:00"
}

###

# DELETE - Excluir um pedido existente
DELETE {{LivrariaAPI_HostAddress}}/api/pedidos/1
