@LivrariaAPI_HostAddress = http://localhost:5145


###

### CRUD Livros ###

# GET - Listar todos os livros
GET http://localhost:5145/api/livros
Accept: application/json

###

# POST - Adicionar um novo livro
POST http://localhost:5145/api/livros
Content-Type: application/json

{
  "titulo": "Senhor dos Aneis",
  "autor": "J. R. R. Tolkien",
  "genero": "Fantasia Medieval",
  "estoque": 10
}

###

# PUT - Atualizar um livro existente
PUT http://localhost:5145/api/livros/8
Content-Type: application/json

{
  "id": 8,
  "titulo": "O Hobbit",
  "autor": "J. R. R. Tolkien",
  "genero": "Fantasia",
  "estoque": 5
}

###

# DELETE - Excluir um livro existente
DELETE http://localhost:5145/api/livros/1

###

### CRUD Clientes ###

# GET - Listar todos os clientes
GET http://localhost:5145/api/clientes
Accept: application/json

###

# POST - Adicionar um novo cliente
POST http://localhost:5145/api/clientes
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@email.com"
}

###

# PUT - Atualizar um cliente existente
PUT http://localhost:5145/api/clientes/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Adam Sandler",
  "email": "adam.sandler@email.com"
}

###

# DELETE - Excluir um cliente existente
DELETE http://localhost:5145/api/clientes/1

###

### CRUD Pedidos ###

# GET - Listar todos os pedidos
GET http://localhost:5145/api/pedidos
Accept: application/json

###

# POST - Adicionar um novo pedido
POST http://localhost:5145/api/pedidos
Content-Type: application/json

{
  "clienteId": 1,
  "livros": [
    { "id": 8 }
    { "id": 9 }
  ],
  "dataPedido": "2024-09-24T00:00:00"
}

###

# PUT - Atualizar um pedido existente
PUT http://localhost:5145/api/pedidos/1
Content-Type: application/json

{
  "id": 1,
  "clienteId": 1,
  "livros": [
    { "id": 1 }
  ],
  "dataPedido": "2024-09-25T00:00:00"
}

###

# DELETE - Excluir um pedido existente
DELETE http://localhost:5145/api/pedidos/1
